In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# Adding names to the columns
import pandas as pd
column_names = ['label', 'id', 'time', 'extra', 'name', 'text']
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Lab07_dataset.csv', encoding='latin-1', names=column_names)
df.head()

label          id                          time     extra             name  \
0      0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY  _TheSpecialOne_   
1      0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY    scotthamilton   
2      0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY         mattycus   
3      0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY          ElleCTF   
4      0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY           Karoli   

                                                text  
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1  is upset that he can't update his Facebook by ...  
2  @Kenichan I dived many times for the ball. Man...  
3    my whole body feels itchy and like its on fire   
4  @nationwideclass no, it's not behaving at all....

In [3]:
# Dropping extra columns
columns_to_drop = ['id', 'time', 'extra', 'name']
df.drop(columns=columns_to_drop, inplace=True)
df.head()

label                                               text
0      0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1      0  is upset that he can't update his Facebook by ...
2      0  @Kenichan I dived many times for the ball. Man...
3      0    my whole body feels itchy and like its on fire 
4      0  @nationwideclass no, it's not behaving at all....

In [4]:
df = df[df['label'].isin([0, 4])].groupby('label').head(5000)
df['label'] = df['label'].replace(4,1)
df

label                                               text
0           0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1           0  is upset that he can't update his Facebook by ...
2           0  @Kenichan I dived many times for the ball. Man...
3           0    my whole body feels itchy and like its on fire 
4           0  @nationwideclass no, it's not behaving at all....
...       ...                                                ...
804995      1  @lbran, thanks for sending us the package - go...
804996      1  @ickleoriental hahahha.. U obviously don't hv ...
804997      1  @juliekoh It's an internet term, but it's spil...
804998      1                         new day.... NEW TRACK!!!! 
804999      1  @foodieguide Okay we need to have a competitio...

[10000 rows x 2 columns]

In [15]:
positive_string_array = df[df['label'] == 1]['text'].tolist()
negative_string_array = df[df['label'] == 0]['text'].tolist()

In [19]:
import re
def remove_links(sentence):
    return re.sub(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', '', sentence)

positive_without_link = [remove_links(sentence) for sentence in positive_string_array]
negative_without_link = [remove_links(sentence) for sentence in negative_string_array]

In [20]:
def remove_at_words(sentence):
    return re.sub(r'@\w+\s?', '', sentence)

positive_without_at_words = [remove_at_words(sentence) for sentence in positive_without_link]
negative_without_at_words = [remove_at_words(sentence) for sentence in negative_without_link]

In [22]:
import re
def remove_punctuation(list_of_string):
  punctuation_marks = [',', '.', '(', ')', '!', '@', '#', '$', '%', '^', '&', '*', '<', '>', '?', ';', ':', '-', '_', '+', '-', '"', "'"]
  list_of_strings = []
  for sublist in list_of_string:
    if isinstance(sublist, str):
      for punctuation_mark in punctuation_marks:
        sublist = sublist.replace(punctuation_mark, '')
        sublist = re.sub(r'\d+', '', sublist)
      list_of_strings.append(sublist)
  return list_of_strings

positive_without_punctuation = remove_punctuation(positive_without_at_words)
negative_without_punctuation = remove_punctuation(negative_without_at_words)

In [25]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords_english = stopwords.words('english')
print(stopwords_english)
def remove_stop_words(sentence):
    words = sentence.split()
    filtered_words = [word for word in words if word.lower() not in stopwords_english]
    return ' '.join(filtered_words)

positive_without_stop_words = [remove_stop_words(sentence) for sentence in positive_without_punctuation]
negative_without_stop_words = [remove_stop_words(sentence) for sentence in negative_without_punctuation]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [29]:
document = positive_without_stop_words + negative_without_stop_words
sentiment = [1] * len(positive_without_stop_words) + [0] * len(negative_without_stop_words)

Count Vectorize

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
count_matrix = CountVectorizer()
count_matrix_final = count_matrix.fit_transform(document)
newarray = count_matrix_final.toarray()

In [40]:
count_matrix.vocabulary_

{'love': 7132,
 'guys': 5232,
 'best': 1154,
 'im': 5966,
 'meeting': 7523,
 'one': 8551,
 'besties': 1160,
 'tonight': 12591,
 'cant': 1862,
 'wait': 13455,
 'girl': 4894,
 'talk': 12108,
 'thanks': 12296,
 'twitter': 12931,
 'add': 116,
 'sunisa': 11903,
 'got': 5046,
 'meet': 7522,
 'hin': 5609,
 'show': 10987,
 'dc': 3008,
 'area': 627,
 'sweetheart': 12017,
 'sick': 11016,
 'really': 10001,
 'cheap': 2066,
 'hurts': 5878,
 'much': 7974,
 'eat': 3680,
 'real': 9990,
 'food': 4491,
 'plus': 9211,
 'friends': 4652,
 'make': 7284,
 'soup': 11411,
 'effect': 3722,
 'everyone': 3983,
 'tell': 12215,
 'burst': 1729,
 'laughing': 6794,
 'loud': 7124,
 'making': 7291,
 'come': 2393,
 'sulk': 11880,
 'thans': 12301,
 'response': 10245,
 'ihad': 5936,
 'already': 361,
 'find': 4339,
 'answer': 512,
 'jealous': 6331,
 'hope': 5727,
 'great': 5111,
 'time': 12464,
 'vegas': 13281,
 'like': 6949,
 'acms': 97,
 'ah': 233,
 'congrats': 2507,
 'mr': 7944,
 'fletcher': 4406,
 'finally': 4336,
 'joi

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
                                                count_matrix_final,
                                                sentiment,
                                                test_size=0.2,
                                                random_state=0)

In [42]:
test = X_test.toarray()

Classifier 01

In [43]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [53]:
pred = classifier.predict(X_test)
pred

array([0, 1, 0, ..., 1, 1, 0])

In [46]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.72      0.74      0.73      1012
           1       0.72      0.71      0.72       988

    accuracy                           0.72      2000
   macro avg       0.72      0.72      0.72      2000
weighted avg       0.72      0.72      0.72      2000



In [47]:
classifier.predict_proba(X_test)

array([[0.71981312, 0.28018688],
       [0.00613808, 0.99386192],
       [0.78578807, 0.21421193],
       ...,
       [0.20035326, 0.79964674],
       [0.01504165, 0.98495835],
       [0.94829434, 0.05170566]])

Classifier 02

In [57]:
from sklearn.naive_bayes import BernoulliNB
classifier2 = BernoulliNB()

In [58]:
classifier2.fit(X_train,y_train)

BernoulliNB()

In [59]:
pred1 = classifier2.predict(X_test)
pred1

array([0, 1, 0, ..., 1, 1, 0])

In [60]:
print(classification_report(y_test, pred1))

              precision    recall  f1-score   support

           0       0.74      0.70      0.72      1012
           1       0.71      0.74      0.73       988

    accuracy                           0.72      2000
   macro avg       0.72      0.72      0.72      2000
weighted avg       0.72      0.72      0.72      2000



In [61]:
classifier2.predict_proba(X_test)

array([[0.62991599, 0.37008401],
       [0.00511244, 0.99488756],
       [0.72807413, 0.27192587],
       ...,
       [0.18943532, 0.81056468],
       [0.01178767, 0.98821233],
       [0.95379642, 0.04620358]])

Comparing Models

In [68]:
mismatch_count = 0
for i in range(len(pred1)):
    if pred[i] != pred1[i]:
        mismatch_count += 1

mismatch_count

106

In [69]:
import numpy as np
count_1_array1 = np.sum(pred1 == 1)
count_1_array2 = np.sum(pred == 1)
if count_1_array1 > count_1_array2:
    print("Model 1 is better")
elif count_1_array1 < count_1_array2:
    print("Model 2 is beter")
else:
    print("Both model are same")

Model 1 is better


LAB 07 QUESTIONS

In [72]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [73]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy', 'Rainy', 'Overcast', 'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
temp = ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']
play=['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']

In [75]:
le = preprocessing.LabelEncoder()
weather_encoded=le.fit_transform(weather)
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)
print("Play:",label)
print("Weather:" ,weather_encoded)

Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]
Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [76]:
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)

Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [77]:
model=MultinomialNB(alpha=0, fit_prior=True)
#model=MultinomialNB(alpha=0, force_alpha=True)
model.fit(features,label)
model.get_params()

/usr/local/lib/python3.10/dist-packages/sklearn/naive_bayes.py:629: FutureWarning: The default value for `force_alpha` will change to `True` in 1.4. To suppress this warning, manually set the value of `force_alpha`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/naive_bayes.py:635: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(


{'alpha': 0, 'class_prior': None, 'fit_prior': True, 'force_alpha': 'warn'}

In [79]:
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


In [80]:
predicted= model.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)

Predicted Value: [1]


In [81]:
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


In [83]:
# Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?
predicted= model.predict([[0,1]])
print("Predicted Value:", predicted)

Predicted Value: [1]


In [85]:
# Will you play if the temperature is ‘Mild’ and weather is ‘Sunny’?
predicted= model.predict([[2,2]])
print("Predicted Value:", predicted)

Predicted Value: [1]
